SENDER_EMAIL = "<SENDER_EMAIL>"
SENDER_PASSWORD = "<SENDER_PASSWORD>"

[ballerina.observe]
tracingEnabled=true
tracingProvider="zipkin"

[ballerinax.zipkin]
agentHostname="localhost"  # Optional Configuration. Default value is localhost
agentPort=9411             # Optional Configuration. Default value is 9411