[package]
org = "nipunal"
name = "create_database"
version = "0.1.0"
distribution = "2201.6.0"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
artifactId = "h2"
version = "2.0.206"
groupId = "com.h2database"
