[package]
org = "nipunal"
name = "online_shopping_combined"
version = "0.1.0"
distribution = "2201.13.4"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
artifactId = "h2"
version = "2.0.206"
groupId = "com.h2database"

[[dependency]]
org="ballerinax"
name="jaeger"
repository="local"
version = "1.1.2"
